modLoader = "javafml"
license = "All Rights Reserved"
loaderVersion = "[47,)"

[[mods]]
modId = "brewincompatdelight"
version = "1.0.3"
displayName = "Brewin Compat Delight"
authors = "DraconicArcher"
credits = "DraconicArcher"
description = "Adds compatability  by adding drinks to Brewin and Chewin from other addons."

[[dependencies.brewincompatdelight]]
modId = "forge"
mandatory = true
versionRange = "[47.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewincompatdelight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewincompatdelight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewincompatdelight]]
modId = "brewinandchewin"
mandatory = true
versionRange = "[1.20.1-3.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewincompatdelight]]
modId = "fruitsdelight"
mandatory = false
versionRange = "[1.0.16,)"
ordering = "NONE"
side = "BOTH"
